version: "3.5"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=veloxidedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thisisnotsecure
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml
      - ./docker/tempo/data:/tmp/tempo
    ports:
      - "14268" # jaeger ingest
      - "6831:6831/udp" # Jaeger protocol
      - "4317:4317" # otlp grpc
      - "3200" # tempo
      - "4318" # otlp http
      - "9411" # zipkin

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  redis:
    image: redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  # Uncomment to use OTEL collector pipeline before Tempo
  # otel-collector:
  #   image: otel/opentelemetry-collector:latest
  #   command: ["--config=/etc/otel-collector.yaml"]
  #   volumes:
  #     - ./docker/otel-collector/otel-collector.yaml:/etc/otel-collector.yaml
  #   ports:
  #     - 14250:14250 # Jaeger
  #     - 4317:4317 # OTLP gRPC
